CC     = gcc
CSRC   = main.c
CFLAGS = -Wall -Wextra -Wl,-rpath ./lib

CXX      = g++
CXXSRC   = main.cc
CXXFLAGS = -Wall -Wextra -Wl,-rpath ./lib

CPPFLAGS = -Idir

LDFLAGS = -Ldir
LDLIBS  = -llibrary

