"
" plugins (To install plugins, execute ':PlugInstall')
"

call plug#begin('~/.vim/plugged')
" file tree
Plug 'scrooloose/nerdtree'
" lsp
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
" for auto completion
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()

"
" options
"

" disable beep sound
set belloff=all

" enable gurbg and curbg on wsl
set t_ut=

" line number
set number

" set width of tab character
set tabstop=2

" add indent automatically
set autoindent

" set width of indent when autoindent is active
set shiftwidth=2

" enable soft tab
if expand("%:t") =~ ".*\.go"
  " if .go file, disable soft tab
  set noexpandtab
else
  set expandtab
endif

" set encoding
set encoding=utf-8

" disable vi compatibility
set nocompatible

" enable spell check
set spell

" ignore Japanese check of Japanese
set spelllang+=cjk

" set number of colors to use
set t_Co=256

" show cursor position
set ruler

" visualize invisible characters
set list
set listchars=tab:»=,trail:=

"
" variables
"

let g:lsp_diagnostics_echo_cursor = 1

"
" key mappings
"
" for nerdtree
map <C-f> :NERDTreeToggle<CR>
" for ctags
map <C-h> :
nnoremap <C-]> g<C-]>
nnoremap <C-h> :vsp<CR> :exe("tjump ".expand('<cword>'))<CR>
nnoremap <C-k> :split<CR> :exe("tjump ".expand('<cword>'))<CR>
" for vim-lsp
" map <C-]> :LspDefinition<CR>
" map <C-e> :LspDocumentFormat<CR>

"
" auto commands
"

" ignore spell check of camel case
fun! IgnoreCamelCaseSpell()
  syntax match CamelCase /\<[A-Z][a-z]\+[A-Z].\{-}\>/ contains=@NoSpell transparent
  syntax match camelCase /\<[a-z]\+[A-Z].\{-}\>/ contains=@NoSpell transparent
  syntax cluster Spell add=CamelCase
  syntax cluster Spell add=camelCase
endfun
autocmd BufRead,BufNewFile * :call IgnoreCamelCaseSpell()

" When editing a file, always jump to the last cursor position
autocmd BufReadPost * if line("'\"") > 0 && line ("'\"") <= line("$") | exe "normal! g'\"" | endif

" templates
" .go
autocmd BufNewFile *.go :0r ~/.vim/templates/template.go
" .html
autocmd BufNewFile *.html :0r ~/.vim/templates/template.html
" .js
autocmd BufNewFile *.js :0r ~/.vim/templates/template.js

"
" others
"

" enable syntax check
syntax enable
" set color scheme
colorscheme molokai
