#
# alias
#

# for unix ls
#alias ls='ls -aG'
# for gnu ls
alias ls='ls --color=auto --all'
alias la='ls'
alias ll='ls -l'


# enable complement
autoload -U compinit
compinit

autoload -U colors
colors

source ~/zsh/.zsh-autosuggestions.zsh

source ~/.git-prompt.sh

# If set nonempty value,
# unstaged (*) and staged (+) changes will be shown next to the branch name.
GIT_PS1_SHOWDIRTYSTATE=1
# If set GIT_PS1_SHOWUPSTREAM="auto",
# "<" indicates you are behind,
# ">" indicates you are ahead,
# "<>" indicates you have diverged
# "=" indicates that there is no difference.
GIT_PS1_SHOWUPSTREAM="auto"
# If set nonempty value,
# '%' will be shown next to the branch name when untracked files exist.
GIT_PS1_SHOWUNTRACKEDFILES=1
# If set nonempty value,
# '$' will be shown next to the branch name if something is stashed.
GIT_PS1_SHOWSTASHSTATE=1

setopt PROMPT_SUBST
PROMPT='${fg[green]}%n@%m ${fg[cyan]}%c ${fg[blue]}(%*)${fg[magenta]}$(__git_ps1)${reset_color}
$ '

#
# initial commands
#

# set default permission of new files and directories
umask 022

# start ssh-agent
eval `ssh-agent`
# add private key
ssh-add

# HACK: Fix bug of wsl: Font settings not working for WSL apps that draw over the entire screen
# See https://github.com/microsoft/Terminal/issues/177
TERM=xterm-color
