#source ~/zsh/zshrc_parts/partial_zshrc_for_mac
source ~/zsh/zshrc_parts/partial_zshrc_for_linux
source ~/zsh/zshrc_parts/partial_zshrc_for_linux_ssh_agent
source ~/zsh/zshrc_parts/partial_zshrc_for_tmux
source ~/zsh/zshrc_parts/partial_zshrc_for_wsl
source ~/zsh/zshrc_parts/partial_zshrc_for_wsl_systemd

# alias
alias la='ls'
alias ll='ls -l'

# enable complement
autoload -U compinit
compinit

source ~/zsh/.zsh-autosuggestions.zsh
source ~/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.git-prompt.sh

# If set nonempty value,
# unstaged (*) and staged (+) changes will be shown next to the branch name.
GIT_PS1_SHOWDIRTYSTATE=1
# If set GIT_PS1_SHOWUPSTREAM="auto",
# "<" indicates you are behind,
# ">" indicates you are ahead,
# "<>" indicates you have diverged
# "=" indicates that there is no difference.
GIT_PS1_SHOWUPSTREAM="auto"
# If set nonempty value,
# '%' will be shown next to the branch name when untracked files exist.
GIT_PS1_SHOWUNTRACKEDFILES=1
# If set nonempty value,
# '$' will be shown next to the branch name if something is stashed.
GIT_PS1_SHOWSTASHSTATE=1

# to use green, cyan, blue ...
autoload -U colors
colors

setopt PROMPT_SUBST
PROMPT='${fg[green]}%n@%m ${fg[cyan]}%c ${fg[blue]}(%*)${fg[magenta]}$(__git_ps1)${reset_color}
$ '

# disable bell
setopt no_beep

# set default permission of new files and directories
umask 022

# for golang
export GOPATH=$HOME/base/codes/github/go
export PATH=$PATH:$HOME/base/codes/github/go/bin

# save command history
HISTFILE=~/.zsh_history
HISTSIZE=6000000
SAVEHIST=6000000
setopt hist_ignore_dups     # ignore duplication command history list
setopt share_history        # share command history data
